# Local Docker Compose Configuration
version: '3.8'

services:
  makao-db:
    image: jchan0211/makao-postgres:latest
    container_name: makao-db
    environment:
      POSTGRES_USER: makao
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: makao-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  
  makao-minio:
    image: jchan0211/makao-minio:latest
    container_name: makao-minio
    environment:
      MINIO_ROOT_USER: "localhost"
      MINIO_ROOT_PASSWORD: "test123456"
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data


volumes:
  postgres-data:
  minio-data: