spring:
  profiles:
    active: db

  application:
    name: makao-api

  # [Todo] 로그에 실행 속도도 작성하기
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        # format_sql: true # SQL 포맷팅
        highlight_sql: true
        # [Todo] 주의 뜨는 이유 찾아보기
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /docs