name: App CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Clean and unit test
        run: ./gradlew clean unitTest

  run-integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Clean and integration test
        run: ./gradlew clean integrationTest